Fix concurrency bug
whyoleg/cryptography-kotlin pull request #26
Opened 2024-03-24 14:58 UTC by emeasure-github-private

Thank you for this excellent library!

I ran into unexpected runtime exceptions while decrypting concurrently on the JVM. The issue appears to be due to a typo in `pooling.kt` (see PR). The proposed change fixes the crashes for my use case.

2024-03-24 18:09 UTC, whyoleg requested changes
Hey! Thank you for fixing it! Somehow I overlooked this...
Could you also please add a small unit test?

2024-03-24 20:13 UTC, emeasure-github-private commented
Sure thing! Attached a small test that fails with the old code.

2024-03-25 10:48 UTC, whyoleg requested changes
Thank you! Still, I would propose to add some more testing of `contract` here.

Note: I do think, that this implementation will evolve (by using approach without locks) and also could be used in other providers (on different platforms) so I would be very happy if there will be tests which properly tests the contract!

2024-03-25 10:48 UTC, whyoleg commented on cryptography-providers/jdk/src/jvmTest/kotlin/PoolingTest.kt
> +    fun testConcurrentAccessOnCachedPoolShouldNotReuseInstances() = runTest {
while testing concurrent access is fine, I would say that we don't really need it here.
We can easily write a sequential test here, something like:
```kotlin
pool.use { i1 -> pool.use { i2 -> pool.use { i3 -> }}}
```
So let's keep both sequential and concurrent variant.

Additionally it would be good to not only count `instantiate` call, but to check, that instances are different.
So f.e make instance an `Int` instead of object and save `instantiateCount` there. And then assert, that the instances used in `use` are different.
And then, we are good to go!

2024-03-26 01:30 UTC, emeasure-github-private commented
> Note: I do think, that this implementation will evolve (by using approach without locks) and also could be used in other providers (on different platforms) so I would be very happy if there will be tests which properly tests the contract!

Good idea! Have you considered borrowing a battle-tested implementation? For example, ktor's [Pool](https://github.com/ktorio/ktor/blob/main/ktor-io/common/src/io/ktor/utils/io/pool/Pool.kt) looks reasonable to me and supports [major platforms](https://github.com/search?q=repo%3Aktorio%2Fktor+path%3ADefaultPool*kt&type=code) (although I didn't notice much in the way of unit testing in that repository).

2024-03-26 01:33 UTC, emeasure-github-private commented
I added an overlapping sequential unit test, simplified a bit, and added some assertSame/NotSame.

2024-03-26 08:14 UTC, whyoleg commented
> Have you considered borrowing a battle-tested implementation?

Yeah, so, most likely I wanted to borrow an idea of pool implementation from okio/ktor/others - I don't want to add additional dependencies for such small thing.
Also, I haven't implemented something more smart, as I do want to implement proper pooling/caching until there will be support for streaming operations or other issues. May be in the end pooling will be not really needed, some benchmarks are needed here.

2024-03-26 08:14 UTC, whyoleg approved these changes
Nice!
Thank you for PR and addressing all of the comments!

2024-03-27 16:13 UTC, emeasure-github-private commented
Makes sense to me! Thanks for the quick review. Looking forward to your next release!

2024-05-13 19:58 UTC, merged