Add ability to use custom IV in AES/GCM
whyoleg/cryptography-kotlin pull request #38
Opened 2024-07-27 22:48 UTC by morki

See #36

2024-08-01 11:07 UTC, whyoleg requested changes
Thanks for the PR and sorry for long delay!

Looks good!
I've started tests, but I do see, that `klib` dump is for some reason missing, have you run `apiDump`?
Also, it would be nice to add additional testing of custom IV in compatibility test like it was added here: https://github.com/whyoleg/cryptography-kotlin/commit/fcd13f568a11cfaa5298a2d4b2afbb6c6408fc84#diff-95b13bb1e657d46d67c27f687519118156c333f974d16a88d646cc6f18d9a6e7

2024-08-02 15:43 UTC, whyoleg commented
Hey @morki, are you still willing to finish PR? Or I could finish it? The reason I'm asking, is that I do have some changes to be merged which will have conflicts.
If I will merge them, this PR is most likely will need to be redone from scratch (by copy-pasting changes)

2024-08-02 21:50 UTC, morki commented
Hi @whyoleg, I was planning to create tests etc, but I am on vacations now, so I can not finnish it for about 3 weeks now. I you want and have time, you can finish this before the changes. If not, that is ok too, I can start from stratch after your changes :)

2024-08-22 19:02 UTC, morki commented
Hi @whyoleg, is it somewhat "stable" now to start to do this PR again from scratch or would you suggest to delay it a bit more due to heavy changes still in progress?

2024-08-22 19:24 UTC, whyoleg commented
Hey!
You can proceed with the changes. May be even not from scratch 😀 

I've decided to postpone big changes for some future release as I was not really happy with the API shape.

2024-09-10 10:04 UTC, whyoleg commented
Hey @morki are you still willing to work on this PR? I'm planning to do a release by the end of September and wanted to include this.

2024-09-10 11:25 UTC, morki commented
Hi @whyoleg, yes I am, will try to finnish it in a couple of days :)

2024-09-10 20:42 UTC, morki commented
I think it is ready for what I can do for it. But it has one problem with tests.

WebCrypto and OpenSSL providers are ok, but JDK are throwing `Cannot reuse iv for GCM encryption`, because of built-in "security" and how are tests working now.

I tried but I really don't know how to solve it. Can you please take a look @whyoleg?

2024-09-18 16:32 UTC, whyoleg requested changes
I'm very sorry again for the long delay, I was not very active last week with my OpenSource projects :(

The changes look fine, thank you! A bit small fixes and we are ready to merge!
I was able to find workaround for JDK GCM IV reuse issue!
Also, could you please run `apiDump` task locally? Without it the CI will fail

2024-09-18 16:32 UTC, whyoleg commented on cryptography-providers-tests/src/commonMain/kotlin/compatibility/AesGcmCompatibilityTest.kt
> +        override fun toString(): String = "CipherParameters(tagSizeBits=${tagSizeBits}, iv.size=${iv?.size})"
`toString` is not needed anymore here as `ByteString` has nice `toString`

2024-09-18 16:32 UTC, whyoleg commented on cryptography-core/src/commonMain/kotlin/algorithms/AES.kt
> +    public interface IvAuthenticatedCipher : IvAuthenticatedEncryptor, IvAuthenticatedDecryptor
Let's make the hierarchy of `IvAuthenticated*` has both `Iv*` and `Authenticated*` characteristics.
so that:
* `IvAuthenticatedEncryptor : AuthenticatedEncryptor, IvEncryptor` - same for decryptor
* `IvAuthenticatedCipher : AuthenticatedCipher, IvCipher, IvAuthenticatedEncryptor, IvAuthenticatedDecryptor`
* add all the same overrides as in `AuthenticatedEncryptor`/`AuthenticatedDecryptor` but for cases when `iv` is provided explicitly

yeah, not very nice, but at least it will be correct. I knew that something like this will happen when I first introduced custom ciphers for AES. Ideally in future it should be generalised similar to `init` parameters as in JDK, but for now it's really needed only for AES. Will see how it could be improved in future when there will be more use-cases for something like this...

Also, while we are here, could you please also make `IvCipher` extends `Cipher` - it was removed by mistake it https://github.com/whyoleg/cryptography-kotlin/commit/eaf13c61ca89e2764154d581565292e8ce8ca8e0

Note: it's fine to merge this PR without those changes, if so, I will do this myself afterwards :)

2024-09-18 16:32 UTC, whyoleg commented on cryptography-providers-tests/src/commonMain/kotlin/compatibility/AesGcmCompatibilityTest.kt
> +                                val ciphertext = cipher.encrypt(iv, plaintext, associatedData)
Okay, I see the issue with JDK IV reuse...
probably something like this could/should be also implemented in CK, but not now

As for now, I've come up with the [following workaround](https://github.com/whyoleg/cryptography-kotlin/commit/9039d298d6cc325975b9b360883546ecef0b116f). Not nice, but for tests it should be fine for now.
Would be nice to apply it in this PR.

2024-09-19 06:52 UTC, morki commented on cryptography-providers-tests/src/commonMain/kotlin/compatibility/AesGcmCompatibilityTest.kt
> +                                val ciphertext = cipher.encrypt(iv, plaintext, associatedData)
Nice workaround, applied :)

2024-09-19 06:53 UTC, morki commented on cryptography-providers-tests/src/commonMain/kotlin/compatibility/AesGcmCompatibilityTest.kt
> +        override fun toString(): String = "CipherParameters(tagSizeBits=${tagSizeBits}, iv.size=${iv?.size})"
Nice catch, removed here and from `AesCbcCompatibilityTest` too.

2024-09-19 06:56 UTC, morki commented on cryptography-core/src/commonMain/kotlin/algorithms/AES.kt
> +    public interface IvAuthenticatedCipher : IvAuthenticatedEncryptor, IvAuthenticatedDecryptor
Here I tried your suggestions, but compiler was complaining, so I tried in another PR based on this one, but I am not very happy with the result, see #45

2024-09-19 06:57 UTC, morki commented
Hey @whyoleg, i fixed those little things and applied your patch to tests. The Cipher interface hierarchy is something over my power, I tried in #45 but don't think it is the right way.

2024-09-19 07:01 UTC, morki commented
Ou, and the `apiDump`. I tried it even before, but locally for me it is failing with:

```
* What went wrong:
Execution failed for task ':cryptography-provider-apple:watchosArm64ApiInfer'.
> There was a failure while executing work items
   > A failure occurred while executing kotlinx.validation.KlibInferAbiWorker
      > The target watchosArm64 is not supported by the host compiler and there are no targets similar to watchosArm64 to infer a dump from it.
```

2024-09-20 04:59 UTC, whyoleg commented
Hm, I see. It needs macOS :)
For this PR probably it should be enough to run `:cryptography-core:apiDump` as only this module has changed it ABI. Could you try it?
If not, I will merge the commits manually after running apiDump on my side.
Otherwise, looks good!

2024-09-20 08:21 UTC, morki commented
I run it and it works, thank you for the guidance :)

2024-09-21 06:39 UTC, whyoleg approved these changes
Once more, thanks for contribution!

CI is green!

2024-09-21 06:39 UTC, merged