Add support for RIPEMD digest
whyoleg/cryptography-kotlin pull request #55
Opened 2024-12-04 08:52 UTC by huskcasaca

RIPEMD160 is widely used and supported by BouncyCastle and OpenSSL3. However, RIPEMD128, RIPEMD256, and RIPEMD320 are not supported by OpenSSL3. I'm not sure if it’s necessary to add the others.

2024-12-05 16:32 UTC, whyoleg requested changes
Thanks for the contribution!

Let's start with just supporting RIPEMD160, as it's supported in at least 2 providers.
This is some kind of "rule" at my side, as I don't see a reason currently to support algorithms, which are available only on one platform (may change in future).
+ as far as I understand, only RIPEMD160 is widely used

2024-12-12 16:31 UTC, whyoleg requested changes
Nice!
Let's try not to change CI configuration

2024-12-12 16:31 UTC, whyoleg commented on .github/workflows/run-tests-compatibility.yml
> +          - os: 'ubuntu-24.04'
is there some problem with `ubuntu-latest`?
There were no problems before, so I don't think that it's needed for this PR
Could you please revert those changes and I will re-run CI?

2024-12-13 03:21 UTC, huskcasaca commented on .github/workflows/run-tests-compatibility.yml
> +          - os: 'ubuntu-24.04'
I tried not to change but `ubuntu-latest` is 22.04 which is using OpenSSL 3.0.2. It dropped RIPEMD160 to legacy providers which requires an extra config file to reenable it otherwise the CI will fail. 
But OpenSSL 3.0.6 reverts the drop so I have to update to `ubuntu-24.04` with OpenSSL 3.0.8+. 

https://github.com/openssl/openssl/issues/16994
https://openssl-library.org/news/openssl-3.0-notes/

2024-12-13 15:44 UTC, whyoleg approved these changes

2024-12-13 15:44 UTC, whyoleg commented on .github/workflows/run-tests-compatibility.yml
> +          - os: 'ubuntu-24.04'
Okay, I see, thanks for the explanation!

2024-12-13 15:44 UTC, merged